- name: Setup 1password
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create the keyrings directory for 1Password
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - 1password
    
    - name: Download 1Password GPG key
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /etc/apt/keyrings/1password.asc
        mode: '0644'
        force: yes
      tags:
        - 1password
    
    - name: Add 1Password APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/1password.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
        state: present
        update_cache: yes
      tags:
        - 1password
    
    - name: Install 1Password CLI
      ansible.builtin.apt:
        name: 1password-cli
        state: present
      tags:
        - 1password

