---
- name: Setup Debian Trixie Dev Machine
  hosts: localhost
  connection: local
  vars:
    dotfiles_repo: "https://github.com/jeff-r/dotfiles.git"
    dotfiles_dest: "{{ ansible_env.HOME }}/dotfiles"
    user: "{{ ansible_env.USER }}"

- import_playbook 1password.yml
- import_playbook apt.yml
- import_playbook docker.yml
- import_playbook ruby_dev.yml
- import_playbook zsh.yml
