---
- name: Setup Ruby and Node
  hosts: localhost
  connection: local
  vars:
    dotfiles_repo: "https://github.com/jeff-r/dotfiles.git"
    dotfiles_dest: "{{ ansible_env.HOME }}/dotfiles"
    user: "{{ ansible_env.USER }}"

  tasks:
    - name: Install rbenv and ruby-build
      ansible.builtin.git:
        repo: https://github.com/rbenv/rbenv.git
        dest: "{{ ansible_env.HOME }}/.rbenv"
        depth: 1
      register: rbenv_installed
      tags:
        - rbenv

    - name: Install ruby-build plugin
      ansible.builtin.git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
        depth: 1
      tags:
        - rbenv

    - name: Configure rbenv in shell
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
        create: yes
        state: present
      tags:
        - rbenv

    - name: Add rbenv init to shell
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: 'eval "$(rbenv init -)"'
        create: yes
        state: present
      tags:
        - rbenv

    - name: Install Ruby 3.3.6
      ansible.builtin.command:
        cmd: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv install 3.3.6"
        creates: "{{ ansible_env.HOME }}/.rbenv/versions/3.3.6"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: no
      tags:
        - rbenv
        - ruby

    - name: Install NVM (Node Version Manager)
      ansible.builtin.shell:
        cmd: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      args:
        chdir: "{{ ansible_env.HOME }}"
      tags:
        - nvm

    - name: Check if Node.js v22.12 is installed
      ansible.builtin.shell:
        cmd: >
          source "{{ ansible_env.HOME }}/.nvm/nvm.sh" && nvm list | grep "v22.12."
      args:
        executable: /bin/bash
      register: nvm_version_check
      failed_when: false
      changed_when: false
      tags:
        - nvm

    - name: Install Node.js v22.12
      ansible.builtin.shell:
        cmd: >
          source "{{ ansible_env.HOME }}/.nvm/nvm.sh" && nvm install 22.12
      args:
        executable: /bin/bash
      when: nvm_version_check.rc != 0
      tags:
        - nvm

